channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5

  - pip=20.1
  - nodejs=14.17.4
  - pip:
    # Define pip packages here.
    # https://pypi.org/
    - robotframework-browser==14.3.0 # https://github.com/MarketSquare/robotframework-browser/releases
    - rpaframework==19.4.2 # https://rpaframework.org/releasenotes.html
rccPostInstall:
  - rfbrowser init
